<?php

/**
 * @file
 * Contains drupal_demos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_demos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_demos module.
    case 'help.page.drupal_demos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demos para el curso de Drupal') . '</p>';
      return $output;

    default:
  }
}
